# this is the file that contains the node's public key signed by the network admin
# it should be created by the administrator on a secure machine
# optionally, this file may be signed by another node instead - in which case the relevant public key should be specified
# in trusted_keyfiles below
# this certificate file also includes other data about the node's identity
node_cert     = 'my_node.crt'

# the 2 files below are generated by gen_node_key.py
node_pubkey   = 'node_public.pem'
node_privkey  = 'node_secret.pem'

# the 2 files below are generated by gen_admin_key.py
admin_pubkey  = 'admin_public.pem'
admin_privkey = 'admin_secret.pem'

# by default, we only trust the admin's public key
trusted_keyfiles = [admin_pubkey]
